/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia2.ejercicio4;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USURIO
 */
public class BusquedaPorRubro extends javax.swing.JInternalFrame {

private DefaultTableModel modelo=new DefaultTableModel();
    /**
     * Creates new form BusquedaPorRubro
     */
    public BusquedaPorRubro() {
        initComponents();
        armarCabecera();
        iniciarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbRubros = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();

        jLabel1.setText("Lista De Productos Por Rubro");

        jbRubros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jbRubrosItemStateChanged(evt);
            }
        });
        jbRubros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRubrosActionPerformed(evt);
            }
        });

        jLabel2.setText("Elija un rubro");

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1)
                        .addGap(0, 132, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbRubros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRubros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRubrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRubrosActionPerformed
        borrarFilas();
        Categoria var=(Categoria)jbRubros.getSelectedItem(); 
        for (Producto prod : SuperDeTodoSA.listaProductos) {
            
            if (prod.getRubro().equals(var)){
            
                modelo.addRow(new Object[]{
                    prod.getCodigo(),
                    prod.getDescripcion(),
                    prod.getPrecio(),
                    prod.getStock()
                        
                });
            }
        }
    }//GEN-LAST:event_jbRubrosActionPerformed

    private void jbRubrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jbRubrosItemStateChanged
        
//        borrarFilas();
//        Categoria var=(Categoria)jbRubros.getSelectedItem(); 
//        for (Producto prod : SuperDeTodoSA.listaProductos) {
//            
//            if (prod.getRubro().equals(var)){
//                
//                modelo.addRow(new Object[]{
//                    prod.getCodigo(),
//                    prod.getDescripcion(),
//                    prod.getPrecio(),
//                    prod.getStock()
//                        
//                });
//                
//                
//            } 
//                
//            
//        }
    }//GEN-LAST:event_jbRubrosItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Categoria> jbRubros;
    private javax.swing.JTable jtProductos;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera(){
        modelo.addColumn("Código");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        jtProductos.setModel(modelo);
    }
    
    private void iniciarCombo(){
        jbRubros.addItem(Categoria.COMESTIBLE);
        jbRubros.addItem(Categoria.LIMPIEZA);
        jbRubros.addItem(Categoria.PERFUMERIA);
        
    }
     private void borrarFilas(){
        
//        int filas=jtProductos.getRowCount()-1;
//        for(int f=filas;f>=0;f--){
//            
//            modelo.removeRow(f);
//        }

    int x = jtProductos.getRowCount() - 1;
        for (; x >= 0; x--) {
            modelo.removeRow(x);
        }
    }

}
